name: Deploy To Server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create .env file from secret
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "."
          target: "/home/${{ secrets.USERNAME }}/assistant"

      - name: SSH - Build and Restart Docker container
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/${{ secrets.USERNAME }}/assistant
            docker stop assistant || true
            docker rm assistant || true
            docker build -t assistant:latest .
            docker run -d --env-file .env --name assistant --network=host -p 1472:1472 assistant:latest
